##########################
# Displayed Bot Messages #
##########################
# You can read about the TOML format at https://toml.io/en/.

[internal]
unknown_command = "Unknown command. Enter 'help' for help or 'exit' to exit."
resource_not_found = "Unable to find resource %s"
get_bot_token = "Enter Discord Bot Token: "
cant_find_token = "Unable to find 'token.txt' from project directory."
set_null_token = "Unable to set null token from file %s"
no_login = "Unable to login to Discord servers, shutting down!"
must_connect = "You have to connect the bot to Discord to use it!"
unable_to_load_account = "Unable to load account data for discord id %d in the accounts database."
cant_access_database = "Unable to access database"
cant_access_jdbc = "Unable to access JDBC SQLite drivers"
inactive_connection = "Unable to check if account %d exists in database with an inactive connection"
cant_save_account = "Unable to save account %d to the database as there is no connection to the database"
cant_save_account_for_id = "Unable to save account data for discord id %d"
cant_close_connection = "Unable to properly close database connection."

[command]
dm_only_command = "You can only use this command in a DM with me"
guild_only_command = "You can only use this command inside of a discord server"
no_console_command = "This command cannot be executed by console"
no_usage = "There is no defined usage for this command."
no_user_command = "This command has no user implementation"
no_console_implementation = "'/%s' does not have a console implementation."
no_register = "Unable to register command '%s' to the main guild"
check_dms = "Check your DMs for command help!"
help_message = """
               **Available Commands:**
               **/balance [user]**: View the balance of an account.
               """
display_balance = "Your balance is $%g"
display_balance_other = "%d's balance is $%g"
account_no_exist = "That account does not exist"
proper_account_id = "You must input a proper account id."
cant_register_command = "Unable to register command '%s' to the main guild"
executed_query = "Executed the query."
account_already_exist = "That account id already exists in memory"
created_account = "Created the account in the system"
cant_load_account = "Unable to load the account from the database"
loaded_account = "Loaded the account from the database"
saved_account = "Saved the account to the database"
deleted_account = "Deleted this account from the database and memory"
account_in_memory = "This account exists in memory"
account_not_in_memory = "This account does not exist in memory"
account_in_sql = "This account exists in the SQL Database"
account_not_in_sql = "This account does not exist in the SQL Database"
account_no_permissions = "This account does not have any permissions"
display_permissions = "Permissions on this account:%s"
account_no_roles = "This account does not have any roles"
display_roles = "Roles on this account:%s"
value_double = "Value must be a double"
value_integer = "Value must be an integer"
set_balance_to = "Set account's balance to $%g"
already_have_permission = "This account already has this permission"
added_permission = "Added permission '%s' to this account"
removed_permission = "Removed permission '%s' from this account"
account_no_permission = "This account does not have this permission"
cleared_permissions = "Cleared all permissions from this account"
already_have_role = "This account already has this role"
added_role = "Added role %d to this account"
removed_role = "Removed role %d from this account"
no_role = "This account does not have this role"
no_roles = "This account does not have any roles"
cleared_roles = "Cleared all roles from this account"

[event]

[other]